# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u673a\u6784\u5c01\u9762\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u673a\u6784\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5e08\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u8272'),
        ),
    ]
