# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 03:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u4ef7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bc4\u4ef7\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bc4\u4ef7\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u4ef7\u59d3\u540d')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8bc4\u4ef7',
                'verbose_name_plural': '\u8bfe\u7a0b\u8bc4\u4ef7',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('course_name', models.CharField(max_length=20, verbose_name='\u8981\u5b66\u4e60\u8bfe\u7a0b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u54a8\u8be2',
                'verbose_name_plural': '\u7528\u6237\u54a8\u8be2',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u5b66\u4e60\u7684\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u59d3\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5b66\u4e60\u8bfe\u7a0b',
                'verbose_name_plural': '\u7528\u6237\u5b66\u4e60\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eID')),
                ('fav_type', models.CharField(choices=[('1', '\u8bfe\u7a0b\u6536\u85cf'), ('2', '\u673a\u6784\u6536\u85cf'), ('3', '\u8bb2\u5e08\u6536\u85cf')], default=1, max_length=5, verbose_name='\u6536\u85cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6536\u85cf\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u7528\u6237ID')),
                ('message', models.CharField(max_length=500, verbose_name='\u7528\u6237\u6d88\u606f')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bfb\u8fc7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6d88\u606f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
    ]
