# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=50, verbose_name='\u8981\u5b66\u4e60\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=300, verbose_name='\u6d88\u606f\u5185\u5bb9'),
        ),
    ]
